#!/bin/bash

#compiler7

if [ -e "$1.asm" ]; then
	../resources/compilers/nja7 $1.asm $1
elif [ -e "$1.nj" ]; then
	../resources/compilers/njc7 $1.nj --output $1.asm
	../resources/compilers/nja7 $1.asm $1
else
	echo "nothing to do"
fi
