#!/bin/bash

#compiler for v5

nj_dir="../nj_files"
asm_dir="../asm_files"
bin_dir="../bin_files"

if [ -e "$asm_dir/$1.asm" ]; then
	./nja5 "$asm_dir/$1.asm" "$bin_dir/$1.bin"
elif [ -e "$nj_dir/$1.nj" ]; then
	./njc5 "$nj_dir/$1.nj" --output "$asm_dir/$1.asm"
	./nja5 "$asm_dir/$1.asm" "$bin_dir/$1.bin"
else
	echo "nothing to do"
fi
