name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Start containers php
      run: docker-compose -f docker-compose_prod.yml build php
        
    - name: Start containers nginx
      run: docker-compose -f docker-compose_prod.yml build nginx
      
    - name: push nginx
      run: docker push  ghcr.io/brytkhalifa/ksptesterbackend-nginx
      
    - name: push php 
      run: docker push ghcr.io/brytkhalifa/ksptesterbackend-php
      
